# maximum DRbMessage size in bytes
# currently set to 8 * default (8 * 25MB)
message_size: 209715200

#list of classes to expose and their ports
security_key: 'to be used when you want to talk to this DRB'
host: localhost
classes:
  - name: "RFM::Lib::DiskCrawler"
    port: 54321
  - name: "RFM::Handlers::TagReader"
    port: 54322
